on:
  push:
    branches: [main]

jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - run: npm i
      - run: npm run lint:actions
      - run: npm run format:actions
