name: Publish Release
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          bodyFile: 'apps/portfolio/CHANGELOG.md,apps/blog/CHANGELOG.md'
          token: ${{ secrets.GITHUB_TOKEN }}
